// <auto-generated />
namespace ChemicalShopping.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class Chemicals : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Chemicals));
        
        string IMigrationMetadata.Id
        {
            get { return "202002191727266_Chemicals"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
